### ISSUE TITLE
Multiple models and models config

### ISSUE THREAD

**Issue by Mandalka** [neelkamath/spacy-server#7]
I consider to use spacy-server for [Open Semantic Search](https://github.com/opensemanticsearch/open-semantic-search) in [Open Semantic ETL](https://github.com/opensemanticsearch/open-semantic-etl), but need to use multiple models, which can be set by HTTP parameter in currently used spacy-services.

Is this (multiple or better configurable multiple models) planed for spacy-server, too?

**Comment by neelkamath** [comment]
I tentatively require multiple models as well. For the v1 release, I tried to get the required components working. I'm currently in the process of trying to implement better integration tests and making it faster. After that, I will try to allow for model configuration. This will take several weeks at the least since I'm currently busy with college exams and projects.

**Comment by Mandalka** [comment]
Thank you for your time and answer.

Its not urgent (i am busy next weeks, too and currently using custom extended spacy-services), i wanted to find out if planed and maybe better to reuse & contribute to issue discussion/maybe code instead of reinventing (or parallel double work) on same wheels.

Another wish/discussion point if one day there will be multiple models (and if easy possible, i am not sure how stable flask is for parallel processing with shared resources things like locking) would be to have the possibility/maybe configurable to load some of the configured models only on first usage to spare RAM for models never used but which maybe will be used (at the moment many models are not used in most (but not all) cases but all loaded to RAM in current used spacy-services).

**Comment by neelkamath** [comment]
I was thinking of creating one Docker image for each model (e.g., `neelkamath/spacy-server:v1-en_core_web_sm`, `neelkamath/spacy-server:v1-en_core_web_lg`, `neelkamath/spacy-server:v1-fr_core_news_sm`). Otherwise images would be massive. I'm yet to properly think it through.

As for potential issues with Flask, I may migrate to something like [FastAPI](https://fastapi.tiangolo.com/) if it's causing problems.

**Comment by neelkamath** [comment]
I'm closing this because it's been fixed in #16. If the fixes don't meet your requirements, feel free to reopen the issue and we can discuss how to improve the architecture.
